package io.robrichardson.banklessbank.ui;

/** Context-menu action ids. */
public enum MenuAction
{
	RELEASE_PLACEHOLDER, RELEASE_ALL_IN_TAB, RELEASE_ALL, NEW_TAB_FROM_ITEM,
	SET_TAB_ICON, CLEAR_TAB_ICON, MOVE_TO_MAIN, DELETE_TAB, COMPACT_TAB, RENAME_TAB,
	IGNORE_PLACEHOLDER, UNIGNORE_PLACEHOLDER, CLOSE_VIEW, CANCEL
}
